version: '2.1'
orbs: 
  codecov: codecov/codecov@3.2.3
  node: circleci/node@5.0.2
  
jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: 
          name: install npm
          command: sudo npm install -g npm@latest

      
      - run: 
          name: run tests
          command: npm run test
          
      - codecov/upload
workflows:
  test_my_app:
    jobs:
      - test
