# version: 2.1
# orbs:
#     codecov: codecov/codecov@3.1.1
#     node: circleci/node@4.7.0
# jobs:
#     build:
#         docker:
#         - image: cimg/node:current
#         steps:
#         - checkout
#         - run:
#                 name:  node/install-packages
#                 command: npm install
#         - run:
#                 name: Running tests and collecting coverage 
#                 command: npm run test
#         - codecov/upload
# workflow:
#     version: 2.1
#     build-test:
#         jobs:
#             - build


version: 2.1
            orbs:
                codecov: codecov/codecov@3.1.1
                node: circleci/node@4.7.0
            workflows:
                upload-to-codecov:

                    jobs:
                        - node/test:
                            post-steps:
                                - codecov/upload