<<<<<<< HEAD
version: '2.1'
orbs: 
  codecov: codecov/codecov@3.2.3
  node: circleci/node@5.0.2
  
jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: 
          name: install npm
          command: sudo npm install -g npm@latest

      
      - run: 
          name: run tests
          command: npm run test
          
      - codecov/upload
workflows:
  test_my_app:
    jobs:
      - test
=======
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
>>>>>>> 9459efac0f2b916479b2ae593cab4bc7dfe2d0b1
